### ISSUE TITLE
Getting Scene Name

### ISSUE THREAD

**Issue by g5fighter** [DapperDino/Mirror-Multiplayer-Tutorials#4]
For some reason when the lobby script is getting the name of the scene provided by the user in the editor instead of giving the name is giving the path. (Unity 2019.4.11f1)

**Comment by DapperDino** [comment]
I think must've been changed in a newer version of Mirror but you can still grab the scene name from the path by getting the string after the final slash.

**Comment by g5fighter** [comment]
Ok, thanks

**Comment by g5fighter** [comment]
But I think is how Unity gets now the string. Finally I used a string putting the scene directly.
